[project]
name = "asyncapi-py"
version = "0.1.0"
description = ""
authors = [
    {name = "ntt-jkorelc",email = "Justin.Korelc@nttdata.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic (>=2.11.7,<3.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
